name: Assign Reviewer
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  assign:
    runs-on: ubuntu-latest
    
    name: Assign Reviewers
    steps:
      - uses: delivery-much/actions-assigner@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          reviewers: raynamharris, jessicalumian 
